### ISSUE TITLE
chown: cannot access '/var/cache/jenkins/': No such file or directory

### ISSUE THREAD

**Issue by LunNova** [binhex/arch-jenkins#3] opened 2016-09-11 10:47 UTC
```
# docker start -i binhex-jenkins
usermod: no changes
[info] Env var PUID  defined as 99
[info] Env var PGID defined as 100
[info] Permissions already set for /config
chown: cannot access '/var/cache/jenkins/': No such file or directory
```

Creating the `/var/cache/jenkins` folder in the container allows it to start.

**Comment by binhex** [comment] 2016-09-11 21:05
Thanks for posting this, the issue is now resolved, a new image has been built on docker hub and has been tested and now starts fine, closing this task.

**Closed as completed by binhex** 2016-09-11 21:05 UTC
